name: Build website with pelican and publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: website
        channels: conda-forge
        environment-file: environment.yml
        auto-activate-base: false
    - name: Build pelican files
      run: |
        pelican .
    - name: rsync files
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: output/
        remote_path: /home/${{ secrets.REMOTE_USER }}/nginx/sites/fbardos
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.REMOTE_KEY }}
